# Generated by Django 4.2.30 on 2026-04-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('gst_no', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('address', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_account', models.CharField(blank=True, max_length=30)),
                ('beneficiary_ifsc', models.CharField(blank=True, max_length=20)),
                ('beneficiary_branch', models.CharField(blank=True, max_length=200)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('financial_year', models.CharField(default='26-27', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin (Full Control)'), ('staff', 'Staff (Invoice Creation & Viewing)')], default='staff', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='superadmin.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
