# Generated by Django 4.2.30 on 2026-05-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_companydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR-1', 'GSTR-1 (Outward Supplies)'), ('GSTR-3B', 'GSTR-3B (Monthly Summary)'), ('GSTR-2B', 'GSTR-2B (Auto ITC Statement)'), ('GSTR-9', 'GSTR-9 (Annual Return)'), ('GSTR-9C', 'GSTR-9C (Reconciliation Statement)'), ('GSTR-4', 'GSTR-4 (Composition Scheme)'), ('TDS Payment', 'TDS Payment (Challan 281)'), ('TDS 24Q', 'TDS Return 24Q (Salary)'), ('TDS 26Q', 'TDS Return 26Q (Non-Salary)'), ('TDS 27Q', 'TDS Return 27Q (NRI Payments)'), ('TCS 27EQ', 'TCS Return 27EQ'), ('Advance Tax', 'Advance Tax'), ('ITR', 'Income Tax Return (ITR)'), ('AIR/SFT', 'AIR / SFT (Fin. Transactions)'), ('PT Return', 'Professional Tax Return'), ('PF Return', 'PF Return (ECR)'), ('ESIC Return', 'ESIC Return'), ('ROC MGT-7', 'ROC Annual Return (MGT-7)'), ('ROC AOC-4', 'ROC Financial Statements (AOC-4)'), ('LUT Filing', 'LUT Filing (GST Export)'), ('Other', 'Other')], max_length=50)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Annual', 'Annual'), ('One-time', 'One-time')], default='Monthly', max_length=20)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('year', models.IntegerField()),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('return_period', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Filed', 'Filed'), ('Late Filed', 'Late Filed')], default='Pending', max_length=20)),
                ('computation_file', models.FileField(blank=True, null=True, upload_to='returns/computation/')),
                ('return_filed_file', models.FileField(blank=True, null=True, upload_to='returns/filed/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='superadmin.company')),
            ],
            options={
                'ordering': ['return_type', '-year', '-month'],
            },
        ),
    ]
