# Generated by Django 4.2.30 on 2026-04-21 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('superadmin', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=50)),
                ('quotation_sequence', models.IntegerField(default=1)),
                ('quotation_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100)),
                ('buyer_order_date', models.DateField(blank=True, null=True)),
                ('dispatch_through', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('gst_type', models.CharField(choices=[('cgst_sgst', 'CGST + SGST (Intra-State)'), ('igst', 'IGST (Inter-State)'), ('exempt', 'GST Exempt')], default='cgst_sgst', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('terms_conditions', models.TextField(blank=True, default='1. No Warranty by physical Damage & Burnt Goods.\n2. If Cheque is Dishonoured Rs. 500/- will be charged.\n3. Any complain regarding goods received must be made within 24 hrs.\n4. Received Above Goods in good condition.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='clients.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='superadmin.company')),
            ],
            options={
                'ordering': ['-quotation_date', '-quotation_sequence'],
                'unique_together': {('company', 'quotation_number')},
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('hsn_sac', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_rate', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['sl_no'],
            },
        ),
    ]
