# Generated by Django 4.2.30 on 2026-04-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, verbose_name='HSN/SAC Code')),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Mtr', 'Mtr'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Pcs', 'Pcs'), ('Box', 'Box'), ('Set', 'Set'), ('Roll', 'Roll'), ('Pair', 'Pair'), ('Job', 'Job')], default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('is_service', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='superadmin.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
