# Generated by Django 4.2.30 on 2026-05-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('TAN', 'TAN Card'), ('PF', 'PF Registration'), ('Aadhaar', 'Aadhaar Card'), ('MSME', 'MSME / Udyam Registration'), ('ESIC', 'ESIC Registration'), ('GST', 'GST Certificate'), ('ITR', 'Income Tax Return'), ('Trade License', 'Trade License'), ('Shops & Establishment', 'Shops & Establishment'), ('Professional Tax', 'Professional Tax'), ('IEC', 'Import Export Code (IEC)'), ('Bank Statement', 'Bank Statement'), ('Other', 'Other')], max_length=50)),
                ('login_id', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='client_documents/')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
        ),
    ]
